export { default as Main } from './Main/Main'
export { default as High } from './High/High'
export { default as Low } from './Low/Low'
export { default as News } from './News/News'
export { default as Save } from './Save/Save'
export { default as Error } from './Error/Error'
